// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCenqmYeJ7-7_wixZ2SpkBBnOjjahGlcgU',
    appId: '1:18285350649:web:3180c08e4b0473c1381c28',
    messagingSenderId: '18285350649',
    projectId: 'dealnest-94f58',
    authDomain: 'dealnest-94f58.firebaseapp.com',
    storageBucket: 'dealnest-94f58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATQJqCYODL5r6s_JERydW3xAPEBYXFpfA',
    appId: '1:18285350649:android:cd2d495f5f033dd7381c28',
    messagingSenderId: '18285350649',
    projectId: 'dealnest-94f58',
    storageBucket: 'dealnest-94f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBsC07ZjVhS2GsiSLCBYqcqg-T-IvDKaY',
    appId: '1:18285350649:ios:266c61037f9ac590381c28',
    messagingSenderId: '18285350649',
    projectId: 'dealnest-94f58',
    storageBucket: 'dealnest-94f58.firebasestorage.app',
    androidClientId: '18285350649-ramoduv5gsqhmc1e3lguj85af2rdscmv.apps.googleusercontent.com',
    iosClientId: '18285350649-ahk8p8pn6t1gq82f9vvmmcuvtqnu5c7d.apps.googleusercontent.com',
    iosBundleId: 'lk.java.dealnest',
  );

}